sudo: false
language: node_js
node_js:
- iojs
- '0.12'
- '0.10'
before_script:
- gem install sass --version "=3.4.18"
- gem install compass --version "=1.0.3"
- npm install -g bower grunt-cli
- bower install
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
env:
  global:
  - GH_REF: github.com/tumetsu/saaksi.git
  - secure: jgJ0zZVlgHFoZkYq3pggPTWt8TEphiN4tHhFLQFqm74bC7n9EfHrldg0TNMlkqcsXBSiqvPJOCdKCzYu9KCPc6+ResbhBVD0ZOAd2h+RfQSDH0i9X46bfjmd5MjQ35u+DYIG2UATSDNhK2IxfWUJyyGE+fJaP4+1kYpqhD6meVZcz5whgixadGJL33UjZvW5Ep1e8KIPw+tcFmAg16FXwGynVc6U1V7Z/kI1nJUiKaJ++BK/t84njUw4yuOAHR9e8S7TBm83Btj7AdsP6BpuyTAKbwQMIAQOjI25NHKANy4lJTTfVIQhFwSoNjB8vN0cvfYhtAgOpBHYBAIME5s+6W/2/XVu2i5WitTkMToxsiURUpnq6bXyi+7gbJIGKRm93TrqWlFVGG9RtC1oWlgCEUpz1IkhoBvSglOaGQQi/qsHieKo2W79VeOf3zEQtG47Pzwth+S7XXZVzm8IIK2wn03YJWIoTlRFGuCFHPl3n5Ugao2w+BJ8Vy73FjagfHbutDIHfDE4S6FHmRGOs5xEgWEkTz1UNQ/A9zbLwyBsdiDTRnLU3O0zBf7bSNo3IDTCWRJIWIwYOhFGJgzNJ+NQyNAMSNFBX3+aJEb7nPu+r2DUPa/XdXo05w6fWveugaeXYvAsRED5hqoDgEdU98cqSEcKKfp4R0LJlebyO1xqZpk=
notifications:
  email: false
  pushover:
    users:
      - secure: ry7Y1CUm+3Cij6WuZ5J1tKPV/en5/JbXik3z8ItcNnYIZGbQNkdllRQWzLAi7FNhezg4cB+VBQosx2CfHLd2N6KLLGeoWB8jQiQEOXD7LUVabZuQnHq/sKwVnEAuXayBO+rTtcwI0VEZaITjA6JbCkcYzj01Wgr98vdosbtQiA94Uo8JOV331aH+tJoVr9ilDeLO7nJA2fyQa1yb+twpcxBbUPvOi8ba7baensvITahiLlztj6MQfTRIXh1uNSUghLMHMw0TEtpR5fcwGEZIxii0UPBfwAorr/70mlpxXXkRB62iuV5eXFg7CbGES5Rm245d+eYC1H5WS+B89VxgtrIZpRrRaIYlUIxszyJynedMg//IYdibb5iQ1V3s0GxzmlLxst8DZfPRGl1eTmLqew61SyCLjcccRohOAmxp5gGnRRQqI9KSAx9TaoCgs3qUfcndgbARhZJW02jZUVNuRMtQDQB1L4PJpMQoBhcKKD8NY2BD5eOLGqSUcbMykiE98h98OEl2b9BZZoRqpMzAGh8Hh4i0KYaNzAusRIORtSviXfnXiLx3StCXTbngU5GtWyEQqTnyrW+5FfXk7D/XLT8ngbRMPYUmTmMsgiqGn7BpF/1P7bQYocETIJDCHZH93nXwAm5z1GCEf/TLyj2Elzq9iUWlVRanCpl/wDZO2Pk=
    api_key:
      - secure: M3/nTJYPPdAM94E804efHvRva1LXjXeZ389HJ1xPCIIlOBIyYaZQNrEOnhvTGSC8W2qJI5QNe+WHa1HO59sv3VbEGg9czdYhBj938QLqTbWF91T/pyptqN6tq/s8qPU1a5Df27wKdvJYZFBpP5OG97ePm0UN1jMF3+kopu48tbG49t8XKJuUz4QdtW6evJVMwqoAIqENKLbyoAybqSE7vYrDdd+uHPZxd81+Zv5I9vluvOM7uBuAKYQ2ovzsTfPqrbxfHXLGFA5XKezsymSfLPGtijXoyUfD/zxDOaMMYKjDBSJKZjs5wXD8JfkrEXO38jPnia1DMxjsyNGDcHgYwDZ4ioE5Pw6CSe+XHEkh9q2gk4PDltnbXKmh+kBRpXeZ/i7GJSHaLMAbyfitwxEYRvTc+dKinWxZspP3NYrPzj+6a7grrzXFdHqvrKCPCqZKpt8CsT5Ppub3DMDbwQVCJA0gaAMRlgCTYgdFlJkOcbjrADy1z3p3AyN1/eVnkc+e7r8wVdlhlXO14lTmLA8yGcmnAD420EAhsGuRyuynjnuKeSKLb6WHvXfnlkQvplU2JHEBVDtfm7msuePCwHVBEYM6fRXqOBY8EWVsZRPNAOzzk0pcUK9rGzmZzE7BK4BF3Tzct0fnuTKuN/13n8bUqBGBvKYhwot+AyHwAkSuLlk=
